#=================================================
# Title: Batch Trigger Build
# Description: This actions will run another workflows with delay from "$DELAY_INT" environment
# Lisence: MIT
# Author: helmiau
# Blog: https://helmiau.com
#=================================================

name: Batch Trigger Build

on:
  workflow_dispatch:
    inputs:
      src_branch:
        type: choice
        description: 'Select immortalwrt branch version:'
        required: true
        default: 21.02
        options:
          - 21.02
          - 23.05
      debug:
        type: choice
        description: 'Enable if you want to testing without triggering any commands.'
        required: true
        default: disable
        options:
          - enable
          - disable

env:
  REPO_OWNER: helmiau
  REPO_NAME: HelmiWrt-OS-Immortal
  BRANCH_NAME: main
  # delay interval in seconds
  DELAY_INT: 150
  # other configs
  FAILPROP: false
  TRIGGERWF: true
  WAITWF: false


jobs:
  Build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq install curl git

      - name: Set Timezone to Asia Jakarta
        uses: szenius/set-timezone@master
        with:
          timezoneLinux: "Asia/Jakarta"

      - name: Load HelmiWrt Mods
        id: mods
        run: |
          mkdir -p workspace
          cd workspace
          git config --global credential.helper store
          git clone https://$GITHUB_REPOSITORY_OWNER:${{ secrets.HELMIWRT_RW }}@github.com/$GITHUB_REPOSITORY_OWNER/HelmiWrt-Plus.git filex
          export UP_USERNEW=$( grep new_user filex/up_info.txt | sed 's/new_user=//g' )
          echo "UP_USERNEW=$UP_USERNEW" >> $GITHUB_ENV
          export UP_NEW=$( grep new_repo filex/up_info.txt | sed 's/new_repo=//g' )
          echo "UP_NEW=$UP_NEW" >> $GITHUB_ENV
          export UP_DEL_OLD=$( grep old_del filex/up_info.txt | sed 's/old_del=//g' )
          echo "UP_DEL_OLD=$UP_DEL_OLD" >> $GITHUB_ENV
          rm -rf filex
          export BUILD_DATE=$(date +"%Y.%m.%d")
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
          sleep 15
          echo "Mods loaded succesfully, resuming build..."

      - name: Create Release Tag for This Repository
        if: ${{ inputs.src_branch }} == 'true'
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: true
          allowUpdates: true
          replacesArtifacts: true
          name: HelmiWrt OS ${{ env.BUILD_DATE }}
          token: ${{ secrets.HELMIWRT_RW }}
          tag: helmiwrt-${{ env.BUILD_DATE }}
          bodyFile: release_body.txt

      - name: Create Release Tag for Upload Repository
        if: ${{ inputs.src_branch }} == 'true'
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: true
          allowUpdates: true
          replacesArtifacts: true
          owner: ${{ env.UP_USERNEW }}
          repo: ${{ env.UP_NEW }}
          name: HelmiWrt OS ${{ env.BUILD_DATE }}
          token: ${{ secrets.HELMIWRT_RW }}
          tag: helmiwrt-${{ env.BUILD_DATE }}
          bodyFile: release_body.txt

      - name: Actions Checkout running succesfully, resuming build
        run: |
          sleep 15
          echo "Actions Checkout running succesfully, resuming build"

      - name: Running Raspberry Pi 1 ${{ inputs.src_branch }} Build
        if: ${{ inputs.src_branch }} == 'disable'
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-rpi1-${{ inputs.src_branch }}.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Raspberry Pi 2 ${{ inputs.src_branch }} Build
        if: ${{ inputs.src_branch }} == 'disable'
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-rpi2-${{ inputs.src_branch }}.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Raspberry Pi 3 ${{ inputs.src_branch }} Build
        if: ${{ inputs.src_branch }} == 'disable'
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-rpi3-${{ inputs.src_branch }}.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Raspberry Pi 4 ${{ inputs.src_branch }} Build
        if: ${{ inputs.src_branch }} == 'disable'
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-rpi4-${{ inputs.src_branch }}.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Armvirt64 ${{ inputs.src_branch }} Build
        if: ${{ inputs.src_branch }} == 'disable'
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-armvirt-${{ inputs.src_branch }}.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Rockchip ${{ inputs.src_branch }} Build
        if: ${{ inputs.src_branch }} == 'disable'
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-rockchip-${{ inputs.src_branch }}.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Sunxi CortexA7 ${{ inputs.src_branch }} Build
        if: ${{ inputs.src_branch }} == 'disable'
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-sunxi-${{ inputs.src_branch }}.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running Sunxi CortexA53 ${{ inputs.src_branch }} Build
        if: ${{ inputs.src_branch }} == 'disable'
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-sunxi-a53-${{ inputs.src_branch }}.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running  x86 32bit ${{ inputs.src_branch }} Build
        if: ${{ inputs.src_branch }} == 'disable'
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-x86-32-${{ inputs.src_branch }}.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"

      - name: Running  x86 64bit ${{ inputs.src_branch }} Build
        if: ${{ inputs.src_branch }} == 'disable'
        uses: convictional/trigger-workflow-and-wait@v1.5.0
        with:
          owner: ${{ env.REPO_OWNER }}
          repo: ${{ env.REPO_NAME }}
          github_token: ${{ secrets.HELMIWRT_RW }}
          workflow_file_name: build-x86-64-${{ inputs.src_branch }}.yml
          ref: ${{ env.BRANCH_NAME }}
          propagate_failure: ${{ env.FAILPROP }}
          trigger_workflow: ${{ env.TRIGGERWF }}
          wait_workflow: ${{ env.WAITWF }}

      - name: Previous build running succesfully, resuming build
        run: |
          sleep $DELAY_INT
          echo "Previous build running succesfully, resuming build"
